### ISSUE TITLE
ERROR: for pseudo_api  Cannot start service pseudo_api: Mounts denied: EOF

### ISSUE THREAD

**Issue by dacostaHugo** [psorianom/pseudo_api#1]
**Hello,**

**I have an issue while launching ./run_docker.sh after setting the PSEUDO_MODEL_PATH in the .env file.**
**Don't really understand where does it come from.**

`killing old docker processes
Going to remove pseudo_api
Removing pseudo_api ... done
building docker containers
Building pseudo_api
Step 1/7 : FROM continuumio/miniconda3
 ---> b4adc22212f1
Step 2/7 : WORKDIR usr/src/pseudo_api
 ---> Using cache
 ---> 4fc09068f87b
Step 3/7 : ADD environment.yml environment.yml
 ---> Using cache
 ---> 4ea39d9cc1ff
Step 4/7 : RUN conda env create -f environment.yml
 ---> Using cache
 ---> 344645bd5d67
Step 5/7 : ENV PATH /opt/conda/envs/flair_pseudo_api/bin:$PATH
 ---> Using cache
 ---> 3fdf613e4993
Step 6/7 : RUN /bin/bash -c "source activate flair_pseudo_api"
 ---> Using cache
 ---> e67600604e36
Step 7/7 : COPY . .
 ---> Using cache
 ---> 80a370c3eba9
Successfully built 80a370c3eba9
Successfully tagged pseudo_api_pseudo_api:latest
Building nginx
Step 1/5 : FROM nginx:1.15.8
 ---> f09fe80eb0e7
Step 2/5 : RUN rm /etc/nginx/nginx.conf
 ---> Using cache
 ---> bdd27fb821fa
Step 3/5 : COPY nginx.conf /etc/nginx/
 ---> Using cache
 ---> e0e7a8625886
Step 4/5 : RUN rm /etc/nginx/conf.d/default.conf
 ---> Using cache
 ---> 873fe1e2f07c
Step 5/5 : COPY project.conf /etc/nginx/conf.d/
 ---> Using cache
 ---> 71112c334b8c
Successfully built 71112c334b8c
Successfully tagged pseudo_api_nginx:latest
Creating pseudo_api ... error

ERROR: for pseudo_api  Cannot start service pseudo_api: Mounts denied: EOF

ERROR: for pseudo_api  Cannot start service pseudo_api: Mounts denied: EOF
ERROR: Encountered errors while bringing up the project.
`

**Here is the docker-compose --verbose up :**
`........
Starting pseudo_api ... error
compose.parallel.feed_queue: Pending: set()

ERROR: for pseudo_api  Cannot start service pseudo_api: Mounts denied: EOF
compose.parallel.parallel_execute_iter: Failed: <Service: pseudo_api>
compose.parallel.feed_queue: Pending: {<Service: nginx>}
compose.parallel.feed_queue: <Service: nginx> has upstream errors - not processing
compose.parallel.parallel_execute_iter: Failed: <Service: nginx>
compose.parallel.feed_queue: Pending: set()

ERROR: for pseudo_api  Cannot start service pseudo_api: Mounts denied: EOF
ERROR: compose.cli.main.main: Encountered errors while bringing up the project.
`

**Do you have any idea where the issue is ?**

**Comment by psorianom** [comment]
Hi @dacostaHugo !  Was your problem solved ? If you still need help, do not hesitate !

**Comment by dacostaHugo** [comment]
Hello ! Just realized the model of your Ano isn't given. I tried to add my BERT one, doesnt work too. May be we can expect a reveal of the "best-model.pt" ;)
